apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-v2
spec:
  selector:
    matchLabels:
      app: music
      version: v2
  replicas: 1
  template:
    metadata:
      annotations:
        readiness.status.sidecar.istio.io/applicationPorts: ""
        sidecar.istio.io/inject: 'true'
      labels:
        app: music
        version: v2
    spec:
      containers:
        - name: music
          image: quay.io/kiali/demo_error_rates_server:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          securityContext:
            privileged: false
          env:
            - name: CODE_REQUESTS
              value: "200,19;500,1"
            - name: SERVER_NAME
              value: "music-v2"
